import { testRange } from "../../helpers";

/**
 *  Gives an array of n random terms
 *
 *  @param {Function} fn the function that generates something random
 *  @param {Number} n number of terms to generate
 *  @param {any[]=} params a potential set of extra params
 *  @returns {Array} an array of length `n` with items generated by `fn`
 *
 *  There can be more parameters after these. All additional parameters are provided to the given function
 */
const n = (fn, n = 1, ...params) => {
  debugger;
  testRange(
    typeof fn !== "function",
    "Chance: The first argument must be a function."
  );

  var i = n;
  var arr = [];

  // Providing a negative count should result in a noop.
  i = Math.max(0, i);

  for (null; i--; null) {
    arr.push(fn.apply(this, params));
  }

  return arr;
};

export default n;
